// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  hero: dynamic(() => import("./Hero")),
  sponsors: dynamic(() => import("./Sponsors")),
};
