// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  showcase: dynamic(() => import("./Showcase")),
  sponsors: dynamic(() => import("./Sponsors")),
  team_members: dynamic(() => import("./TeamMembers")),
  testemonials: dynamic(() => import("./Testemonials")),
};
